### ISSUE TITLE
App crashes spontaneously while drawing

### ISSUE THREAD

**Issue by ConschiB** [4Q-s-r-o/signature#100]
First of all, thanks for this package, I do like it a lot!

However, recently I got noticed that a few users experienced app crashes while or after drawing a signature. I saw these crashes also on Firebase Crashlytics. 

<img width="1240" alt="image" src="https://github.com/4Q-s-r-o/signature/assets/101922816/fb86129a-4a31-4b50-88df-390d9cdb369b">

Is this a known issue or is there any way to avoid this?

(I use the Signature Component exactly like the example-code in the ReadMe section on PubDev)

**Comment by egfconnor** [comment]
I am seeing the same issue.

**Comment by MartinHlavna** [comment]
This is interesting, it looks like the setState itsfelt is crashing.

@egfconnor can you maybe reproduce this? Maybe there are another errors in logs that may shine some light on this.

**Comment by justinlettau** [comment]
I also see this in logs, but haven't been able to reproduce it locally. Using signature v5.5.0. 

Stack trace:

```
TypeError: Null check operator used on a null value
  #0      State.setState (package:flutter/src/widgets/framework.dart:1223)
  #1      SignatureState._addPoint (package:signature/signature.dart:174)
  #2      SignatureState.build.<fn>.<fn> (package:signature/signature.dart:112)
  #3      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:3078)
  #4      GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:481)
  #5      RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:450)
  #6      GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:426)
  #7      GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:389)
  #8      GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:336)
  #9      GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:305)
  #10      _invoke1 (dart:ui/hooks.dart:328)
  #11      PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442)
  #12      _dispatchPointerDataPacket (dart:ui/hooks.dart:262)
```

**Comment by ethael** [comment]
closing. unable to reproduce
